name: Build & Release Lobby Lockdown EXE

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build executable
        run: pkg . --targets node18-win-x64 --output dist/lobby-lockdown.exe

      - name: Download rcedit
        run: Invoke-WebRequest -Uri "https://github.com/electron/rcedit/releases/latest/download/rcedit-x64.exe" -OutFile rcedit.exe

      - name: Apply icon
        run: ./rcedit.exe dist/lobby-lockdown.exe --set-icon assets/lobby-lockdown.ico

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV

      - name: Create tag and push it using PAT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag main-${{ env.sha_short }}
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main-${{ env.sha_short }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main-${{ env.sha_short }}
          name: "Auto Release from main - ${{ env.sha_short }}"
          files: dist/lobby-lockdown.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}